/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
  id("java-library")

  // Apply the Kotlin JVM plugin to add support for Kotlin.
  kotlin("jvm")

  // Apply the application plugin
  application
}

dependencies {
  // libary module.
  implementation(project(":core"))

  // -- Tests ---

  // Use the Kotlin test library.
  testImplementation(kotlin("test"))

  // Use the Kotlin JUnit integration.
  testImplementation(kotlin("test-junit"))
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
  mainClass.set("de.nox.dndassistant.cui.TermGuiKt")
}

//tasks.withType<Jar> {
//  manifest {
//    attributes["Main-Class"] = "de.nox.dndassistant.cui.TermGuiKt"
//  }
//  from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) }) {
//    exclude("META-INF/*.RSA", "META-INF/*.SF", "META-INF/*.DSA")
//  }
//}
